shared:
    image: gcc

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - setup: |
                apt-get update && apt-get install -y python3-pip
                pip3 install gcovr
            - build: make cleanplatforms platforms testcoverageplatforms sonarcoverage
