shared:
    image: gcc

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - build: make
            - setup: export BUILD_DIR=$(pwd)/build && echo $BUILD_DIR
            - run-test: valgrind --xml=yes --xml-file=$BUILD_DIR/valgrind-report.xml $BUILD_DIR/test_component1 --gtest_output=xml:$BUILD_DIR/xunit-report.xml
            - coverage: gcovr -x -r . > $BUILD_DIR/gcovr-report.xml