shared:
    image: gcc
    environment:
        TEST_ENV: "a b c"
        SD_ZIP_ARTIFACTS: true

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - setup: |
                apt-get update
                apt-get install -y cmake libgtest-dev python3-pip
                pip3 install gcovr
                bash +x install-gtest.sh
            - build: make cleanplatforms platforms testcoverageplatforms sonarcoverage
