shared:
    image: gcc

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - build: make
            - setup: |
                export BUILD_DIR=$(pwd)/build && echo $BUILD_DIR
                apt-get update && apt-get install -y python3-pip
                pip3 install gcovr
            - run-test: $BUILD_DIR/test_component1 --gtest_output=xml:$BUILD_DIR/xunit-report.xml || true
            - coverage: gcovr -x -r . > $BUILD_DIR/gcovr-report.xml