shared:
    image: gcc
    environment:
        TEST_ENV: "a b c"
        SD_ZIP_ARTIFACTS: true
        SD_SONAR_OPTS: '-Dsonar.projectVersion=abc -Dsonar.projectVersion=cdf'

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - setup: |
                cp $SD_META_PATH $SD_ARTIFACTS_DIR
                apt-get update
                apt-get install -y cmake libgtest-dev python3-pip
                pip3 install gcovr
                bash +x install-gtest.sh
            - build: make cleanplatforms platforms testcoverageplatforms sonarcoverage
