shared:
    image: gcc

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - setup: |
                sleep 120
                meta set tests.coverage 100
                meta set tests.results 10/10
                apt-get update
                apt-get install -y cmake libgtest-dev python3-pip
                pip3 install gcovr
                bash +x install-gtest.sh
            - build: make cleanplatforms platforms testcoverageplatforms sonarcoverage
