shared:
    image: gcc
    environment:
        TEST_ENV: "a b c"
        SD_SONAR_OPTS: '-Dsonar.projectVersion=abc -Dsonar.projectVersion=$SD_BUILD_ID'

jobs:
    main:
        requires: [~pr, ~commit, ~sd@371:detached]
        steps:
            - echo-new: echo new
            - env: env
            - setup: |
                meta get commit.author
                cp $SD_META_PATH $SD_ARTIFACTS_DIR
                apt-get update
                apt-get install -y cmake libgtest-dev python3-pip
                pip3 install gcovr
                bash +x install-gtest.sh
            - build: make cleanplatforms platforms testcoverageplatforms sonarcoverage
